#!/bin/bash
LOG_FILE="./logs/app.log"
echo "============================================"
echo "  LOG ANALYSIS REPORT - $(date)"
echo "============================================"
echo " Total lines:  $(wc -l < $LOG_FILE)"
echo " ERROR count:  $(grep -c 'ERROR' $LOG_FILE || echo 0)"
echo "WARN count:   $(grep -c 'WARN' $LOG_FILE || echo 0)"
echo " INFO count:   $(grep -c 'INFO' $LOG_FILE || echo 0)"
echo ""
echo "All ERROR messages:"
grep "ERROR" $LOG_FILE
echo ""
echo "Root Cause Analysis:"
grep -q "ECONNREFUSED" $LOG_FILE && echo "  DB connection refused - check if DB is running"
grep -q "Out of memory" $LOG_FILE && echo "  OOM - increase container memory limit"
grep -q "Authentication failed" $LOG_FILE && echo "  Auth failures - check credentials"
grep -q "TypeError" $LOG_FILE && echo "  TypeError - add null checks in code"
echo "============================================"
